# Site settings
title: Alamgir Hossain | Blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.sfu.ca/~mahossai/"
author:
  name: "Alamgir Hossain"
  url: "http://www.sfu.ca/~mahossai/"
email: "alamgirmath@gmail.com"
# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

googlescholar_username: citations?user=UabU-5gAAAAJ&hl=en # Google Scholar
researchgate_username: M_Alamgir_Hossain # Research Gate
twitter_username:     alamgirmath1  # Replace this with your Twitter username
github_username:      alamgirh  # Replace this with your GitHub username
# researchgate_username:  profile/M_Alamgir_Hossain  # Replace this with your Dribbble username
linkedin_username:   m-alamgir-hossain-60b6a734  # Replace this with your LinkedIn username
# google_plus_username: u/0/102679449971781768694  # Replace this with your Google+ username
facebook_username:    alamgir.hossain.507  # Replace this with your Facebook username
# dribbble_username:    example  # Replace this with your Dribbble username

# Options
custom_header: false
custom_nav_footer: false
reverse: false
